# This is an example with only required properties:
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    ignored_updates:
      - match:
          dependency_name: "ember-cli"
      - match:
          dependency_name: "ember-source"
      - match:
          dependency_name: "ember-data"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
