name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: yarn
      run: yarn

    - name: test all packages
      run: yarn workspaces foreach -pv run test --test-port=0
