name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: yarn --version
      run: yarn --version

    - name: list yarn plugins
      run: yarn plugin list

    - name: list yarn cache
      run: ls -l .yarn/cache

    - name: yarn
      run: yarn

    - name: list node_modules
      run: ls -l node_modules

    - name: ls node_modules/@babel/compat-data/corejs3-shipped-proposals
      run: ls node_modules/@babel/compat-data/corejs3-shipped-proposals

    - name: test
      run: yarn test
